name: Update Market Data

on:
  schedule:
    # Uruchamiaj codziennie o 00:00 UTC (czyli 1:00 lub 2:00 w Polsce)
    - cron: '0 0 * * *'
  workflow_dispatch: # Pozwala uruchomić ręcznie przyciskiem (do testów)

permissions:
  contents: write

jobs:
  update-stonks:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v3

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Zainstaluj biblioteki
        run: pip install requests

      - name: Uruchom skrypt giełdowy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_stonks.py

      - name: Zapisz zmiany w bazie danych
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📈 Auto-update: Notowania giełdowe"
          file_pattern: stonks.json
